name: Build and Release - DB

on:
  push:
    branches:
      - main
      - 'db/*'
      - 'cicd/*'
env:
  AWS_REGION: "eu-west-1"
  FW_USER: ${{ secrets.DB_USERNAME }}
  FW_PASS: ${{ secrets.DB_PASSWORD }}
  FW_URL: ${{ secrets.DB_URL }}

permissions:
  id-token: write
  contents: read

jobs:
  FlywayMigration:
    name: Run Flyway Migration

    runs-on: ubuntu-latest

    steps:
      - name: Continuous Integration Flyway Clean Migrate
        uses: actions/checkout@v3.0.0

      - run: wget -qO- https://download.red-gate.com/maven/release/com/redgate/flyway/flyway-commandline/10.7.1/flyway-commandline-10.7.1-linux-x64.tar.gz | tar -xvz && sudo ln -s `pwd`/flyway-10.7.1/flyway /usr/local/bin
      - run: flyway -user="${{ secrets.DB_BUILD_USERNAME }}" -password="${{ secrets.DB_BUILD_PASSWORD }}" -url="${{ secrets.DB_BUILD_URL }}" info
      - run: flyway -user="${{ secrets.DB_BUILD_USERNAME }}" -password="${{ secrets.DB_BUILD_PASSWORD }}" -url="${{ secrets.DB_BUILD_URL }}" migrate